import type { Metadata } from 'next'
import { Inter_Tight, Geist_Mono } from 'next/font/google'
import localFont from 'next/font/local'

import './globals.css'
import { ReactQueryClientProvider } from '@/components/others/query-client-provider'

const interTight = Inter_Tight({ variable: '--font-inter-tight', subsets: ['latin'] })
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] })
const display = localFont({ variable: '--font-display', src: '../assets/fonts/compressed.woff2' })
const regular = localFont({ variable: '--font-regular', src: '../assets/fonts/regular-web.woff2' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const viewport = {
  width: 'device-width',
  initialScale: 1,
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang='en'>
        <head>
          <link rel='manifest' href='/manifest.json' />
          <meta name='theme-color' content='#ffffff' />
          <meta name='mobile-web-app-capable' content='yes' />
          <meta name='apple-mobile-web-app-capable' content='yes' />
          <meta name='apple-mobile-web-app-status-bar-style' content='default' />
        </head>
        <body className={`${interTight.variable} ${geistMono.variable} ${display.variable} ${regular.variable} antialiased`}>
          <main className='flex justify-center h-dvh w-full'>{children}</main>
        </body>
      </html>
    </ReactQueryClientProvider>
  )
}

