export { arenas } from '@/db/schemas/arena'
export { arenasRelations, players, playersRelations } from '@/db/schemas/player'
export type { NewPlayer, Player } from '@/db/schemas/player'
export { teams, teamsRelations } from '@/db/schemas/team'
export type { NewTeam, Team } from '@/db/schemas/team'
